// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ctiJCfISvwsJSs_8-SdVbqPMcK-_ngs',
    appId: '1:447956435710:web:2d2539ca70f91d64cb9baf',
    messagingSenderId: '447956435710',
    projectId: 'fasum-app-16ccb',
    authDomain: 'fasum-app-16ccb.firebaseapp.com',
    storageBucket: 'fasum-app-16ccb.appspot.com',
    measurementId: 'G-XHRCLZ8P0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2sRW-aoPKUhKb9IJVuPfzUiVAgmPaO0U',
    appId: '1:447956435710:android:52deccfec2075b7fcb9baf',
    messagingSenderId: '447956435710',
    projectId: 'fasum-app-16ccb',
    storageBucket: 'fasum-app-16ccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsHc-DOs-yGENm3tQmrnUnF_xRaAEzJDM',
    appId: '1:447956435710:ios:dcf1b51e5d8f1ac1cb9baf',
    messagingSenderId: '447956435710',
    projectId: 'fasum-app-16ccb',
    storageBucket: 'fasum-app-16ccb.appspot.com',
    iosClientId: '447956435710-snqarop8vstctaftjbgo3f19vvqitsu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsHc-DOs-yGENm3tQmrnUnF_xRaAEzJDM',
    appId: '1:447956435710:ios:dcf1b51e5d8f1ac1cb9baf',
    messagingSenderId: '447956435710',
    projectId: 'fasum-app-16ccb',
    storageBucket: 'fasum-app-16ccb.appspot.com',
    iosClientId: '447956435710-snqarop8vstctaftjbgo3f19vvqitsu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ctiJCfISvwsJSs_8-SdVbqPMcK-_ngs',
    appId: '1:447956435710:web:762487655db034bccb9baf',
    messagingSenderId: '447956435710',
    projectId: 'fasum-app-16ccb',
    authDomain: 'fasum-app-16ccb.firebaseapp.com',
    storageBucket: 'fasum-app-16ccb.appspot.com',
    measurementId: 'G-6KWL52YCEW',
  );

}